### ISSUE TITLE
Oct 9, 2020 Windows build may be broken

### ISSUE THREAD

**Issue by OlegAlexander** [kevinlawler/kona#607] opened 2021-08-21 17:30 UTC
Hello and thank you for creating Kona. 

I'd like to report that the Oct 9, 2020 Windows build may be broken. Here's what I get when I run k.exe under cmd:

[klog.txt](https://github.com/kevinlawler/kona/files/7025917/klog.txt)

The previous release from Mar 14, 2020 works fine. Thank you.

**Comment by tavmem** [comment] 2021-08-22 01:00
Oops ... it's not a broken build.
It looks like I uploaded a Windows build from [tavmem/ks] instead of from [kevinlawler/kona].

Sometimes, when attempting to resolve a kona issue, it is useful to see what kona is doing each step of the way.
[tavmem/ks] is kona with stack reporting.
There is a script that formats the output that you got, so you can easily follow the execution stack and examine intermediate results.

Once the cause of a problem is identified and fixed in [tavmem/ks], the fix should be implemented in [kevinlawler/kona] and then the Windows build should be uploaded from [kevinlawler/kona].
Looks like I uploaded the build from the wrong place.

I would upload the correct Windows build, but my Windows environment totally crashed.
It may take me some time to recreate it.

Thanks for pointing out this mistake !!!

**Comment by tavmem** [comment] 2021-12-25 20:55
Release published on Dec 25, 2021 has the correct version of k.exe:
- from kevinlawler/kona
- instead of from tavmem/ks

**Closed by tavmem** 2021-12-25 20:55 UTC
Labels: cleanup
