### ISSUE TITLE
Requesting with HTTP

### ISSUE THREAD

**Issue by silgon** [kevinlawler/kona#467] opened 2017-08-03 11:33 UTC
I have a simple question (for which I cannot find an aswer). Let's say I start kona with the following command.

```
./k -h 8080
```

I should be able to talk to the server to get a result. When using `kdb+` I can run it with `q -p 8080` and do a request with `curl localhost:8080/a:10`. I tried the same with `kona` but it doesn't work and I have no idea how to trigger the queries. Thanks in advance.

**Comment by tavmem** [comment] 2017-08-05 16:06
I think that this did work at one time.  
Sounds like a regression that is not covered in our suite of tests.

**Comment by silgon** [comment] 2017-08-06 10:16
And, what do you usually use to communicate kona with another program? A socket or something? I didn't find anything in the tutorial (or I skipped something). Thanks!

**Comment by tavmem** [comment] 2017-08-07 12:20
There were 3 ways for kona to communicate with another program:

1.  Sockets:  used primarily when the other program was another instance of kona (or k).   This is currently working in many OSes.  It is not working properly in NetBSD and OpenBSD.  (See isssue 448).

2.  HTTP:  I think this was working at one time.  See issues 210, 346 and 347.

3.  Kona as a shared library with a definitive C api.  There seems to be a regression there also.  
See https://groups.google.com/forum/#!topic/kona-dev/pXl8qpuKJ0s
in the Google group "Kona Developers"

**Comment by bakul** [comment] 2017-08-08 07:50
First note that kona emulates k3, *not* k4 (the underlying language of q).
Command line option -h seems to work as per spec (with some bugs) but it may not do what you may have expected. For example, Try

    $ ./k -h 8888

and then from another window do the following

    $ telnet localhost 8888
    GET / http/1.1.

you should see the same text echoed back and the telnet connection terminated. Next in the k server window, set the `m.h` filter:

         .m.h:{` 0:x; x,x}

now if you start `telnet` again and type the `GET` line, this line will be echoed on the k server console window as well as doubled and sent back stream to telnet before closing the connection.

One small bug is that newline is eaten up (you should get two GET lines, not one line with two GETs).

Another: there is some noise in the k server window every time  the connection terminates.

k3 does very little with either `-i` or `-h`. The idea is you give k3 a script which defines its behavior and then have that script process user requests. -h string is given to a `.m.h` if defined. `-i` seems to be for k to k communication. The default is to evaluate the given string. `handle 3: expr` is async in the server (nothing comes back) and is given to the `.m.s` filter. `handle 4: expr` is sync. and a result is returned. This is ginve to `.m.g` filter, which yields a value.

In kona you have to specific `-h port` or `-i port` before the script, while in k3 the script comes first and you can provide additional arguments after the port spec.

There are a number of issues with IPC in kona....

**Comment by silgon** [comment] 2017-08-16 15:22
Sorry for taking long time to reply.
@tavmem is there any tutorial using connections with sockets?

@bakul I tested `./k -h 8888` in the first console and in a second console with telnet the following happens.
```
$ telnet localhost 8888
Trying ::1...
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
     .m.h:{` 0:x; x,x}  # I wrote this line
     .m.h:{` 0:x; x,x}  # it was echoed back
Connection closed by foreign host.

$ telnet localhost 8888
Trying ::1...
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
GET / http/1.1.
GET / http/1.1.
Connection closed by foreign host.
```
It doesn't exit as you say, `telnet` replies the same, but it doesn't matter the message I sent. Then the other terminal with the `k` command doesn't say anything at all. I'm using the `master` branch. Probably I'm doing something silly wrong. I'll try to play around and see what happens.

**Comment by silgon** [comment] 2017-08-16 15:28
Sorry for taking long time to reply.
@tavmem is there any tutorial using connections with sockets?

@bakul I tested `./k -h 8888` in the first console and in a second console with telnet the following happens.
```
$ telnet localhost 8888
Trying ::1...
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
     .m.h:{` 0:x; x,x}  # I wrote this line
     .m.h:{` 0:x; x,x}  # it was echoed back
Connection closed by foreign host.

$ telnet localhost 8888
Trying ::1...
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
GET / http/1.1.
GET / http/1.1.
Connection closed by foreign host.
```
It doesn't exit as you say, `telnet` replies the same, but it doesn't matter the message I sent. Then the other terminal with the `k` command doesn't say anything at all. I'm using the `master` branch. Probably I'm doing something silly wrong. I'll try to play around and see what happens.

**Comment by tavmem** [comment] 2017-08-18 01:25
In the Kona Wiki, in the section on Links ...
there are links to the K 2.0 User Manual and the K 2.0 Reference Manual.
There are quite good descriptions of the use of sockets in k (esp. in the Reference Manual).

**Comment by tavmem** [comment] 2020-03-02 04:35
This issue concerns how to do interprocess communication between 2 k processes.
The k2.0 reference manual section ```11: I/O and Communication ``` describes how this is done in k, and it appears to be working in kona.   Example:
set up 1st process
```
$ rlwrap -n ./k -i 1234
kona      \ for help. \\ to exit.
```
set up 2nd process and communication handle, and execute a "set" message:
```
$ rlwrap  -n ./k
kona      \ for help. \\ to exit.

  3: (`"172.20.2.16"; 1234)
3
  3 3: "a:2+3"
```
check the "set" message in the 1st process:
```
  a
5
```
do a "get" message in the 2nd process:
```
  3 4: `a
5
```
close the handle in the 2nd process:
```
  3: 3
```

I am closing this issue.

**Closed** 2020-03-02 04:36 UTC
Labels: bug
